name: Generate UML Diagram

on:
  push:
    branches:
      - ebi1

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install PlantUML Class Diagram Generator
        run: dotnet tool install PlantUmlClassDiagramGenerator --tool-path ./.dotnet/tools
      - name: Add tools to PATH
        run: echo "$GITHUB_WORKSPACE/.dotnet/tools" >> $GITHUB_PATH
      - name: Generate UML
        run: |
          mkdir -p Docs/uml
          puml-gen Assets/Scripts Docs/uml -dir -ignore bin,obj,Properties -createAssociation -allInOne
      - name: Render UML to SVG
        run: |
          sudo apt-get install -y default-jre graphviz
          curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar
          java -jar plantuml.jar -tsvg Docs/uml
